import puppeteer from 'puppeteer-core';
const S = '/private/tmp/claude-501/-Users-saifsiddiqui-Developer-Workspace-saif-portfolio/fcbbf90d-26a7-4321-83a5-94bdc853e064/scratchpad';
const b = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'shell', args: ['--no-sandbox'] });
const page = await b.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.setViewport({ width: 1440, height: 900, deviceScaleFactor: 2 });
await page.goto('https://saifsiddiqui.in/studio', { waitUntil: 'domcontentloaded' });
await page.evaluate(() => window.localStorage.setItem('studio:key', 'bVAv35ArVcOLCs3a8pl6HPdR'));
await page.reload({ waitUntil: 'networkidle0' });
await page.waitForSelector('.studio-apps button');
await page.evaluate(() => [...document.querySelectorAll('.studio-apps button')].find((x) => x.textContent === 'Apply').click());
await page.waitForSelector('.apply-drop', { timeout: 20000 });
await new Promise((r) => setTimeout(r, 600));
const box = await page.$eval('.apply-drop', (e) => { const r = e.getBoundingClientRect(); return { w: Math.round(r.width), h: Math.round(r.height), x: Math.round(r.x) }; });
console.log('drop zone:', box);
console.log('has url field:', (await page.$$('#apply-url')).length === 1);
console.log('has paste-text:', (await page.$$('.apply-paste')).length === 1);
console.log('hint:', (await page.$eval('.apply-hint', (e) => e.textContent)).trim());
await page.screenshot({ path: S + '/apply-desktop.png' });
console.log('js errors:', errors.length ? errors : 'none');
await b.close();
